### ISSUE TITLE
Port extension to Ulauncher 5

### ISSUE THREAD

**Issue by paualberto** [Ulauncher/ulauncher-timer#3]
Ulauncher 5 (of which development builds are already available) will ship the Python 3 version only. As a result, all extensions have to be ported to Python 3, and also the new Ulauncher Extension API v2.

See [more details here](http://docs.ulauncher.io/en/latest/extensions/migration.html#migrate-from-api-v1-to-v2-0-0)

**Comment by gornostal** [comment]
Thanks for the reminder @paualberto 
Updating all official extensions including this one is in my todo list.

**Comment by paualberto** [comment]
Oh right, sorry for opening the issue on official extensions.  
Daily reminder I guess :stuck_out_tongue: 

Thanks for all your work!

**Comment by gornostal** [comment]
no worries ;)

**Comment by gornostal** [comment]
done
