### ISSUE TITLE
 Unexpected API error. HTTPError:

### ISSUE THREAD

**Issue by anibal-aguila** [Ulauncher/ulauncher-timer#4]
![image](https://user-images.githubusercontent.com/49025536/58491658-b33d4200-816f-11e9-9150-465273a41112.png)

**Comment by Prn-Ice** [comment]
I've also got this

**Comment by gornostal** [comment]
Hi @anibal-aguila 
When you opened this issue you've ignored the template for a bug report. Could you update the description filling in all the required info about the bug, please?

Thanks

**Comment by gornostal** [comment]
@anibal-aguila what version of Ulauncher are you using?

**Comment by anibal-aguila** [comment]
@gornostal 4.4.0.r1
:)

**Comment by v-marinkov** [comment]
I also confirm the error on the same version of Ulancher

**Comment by rprihoda** [comment]
Samsies 4.4.0r1/ Fedora 30/ Gnome Version 3.32.2

**Comment by gornostal** [comment]
Fixed

**Comment by erfanr** [comment]
I have the same issue. Ulauncher 4.4.0.r1 and fedora 30. Installed it yesterday. Are there any newer version for fedora?

**Comment by gornostal** [comment]
@erfanr sorry for the delayed reply. Could you create a new issue if it's still actual for you?
